-- Add pari tokens and ad recharge timestamps to Player
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "pariTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "pariTokensUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "lastAdPariAt" TIMESTAMP(3);
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "lastAdQuizAt" TIMESTAMP(3);
